command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
env:
  - name: HB_CATALOG
    value: lr_dev_aws_us_catalog
  - name: HB_SCHEMA
    value: hb_renewal
  - name: HB_WAREHOUSE
    value: a3b61648ea4809e3
  - name: HB_LLM_ENDPOINT
    value: databricks-claude-sonnet-4-5
  - name: DATABRICKS_HTTP_PATH
    value: /sql/1.0/warehouses/a3b61648ea4809e3
  - name: HB_GENIE_SPACE_ID
    value: 01f19d63fe03198a95c55b64a81ea535
  - name: HB_DASHBOARD_ID
    value: 01f19d737ef41c468039d889d47d91a9
  - name: ENABLE_SELFFUNDED
    value: "true"
